version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Configurar entorno de pruebas
          command: echo "Configurando entorno de pruebas..."

  install_dependencies:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: | 
            npm install 

  verify_dependencies:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Verificar dependencias
          command: |
            ls -R node_modules/chai node_modules/chai-http

  install_npm_force_resolution:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Install chai and chai-http explicitly
          command: |
            npm install
            npm list rimraf

  install_chai_and_chai_http:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Install chai and chai-http explicitly
          command: 
            npm install chai chai-http

  run_tests:
    docker:
      - image: cimg/node:18.20.0
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: |
            npx mocha --loader --timeout 15000 src/test/*.js --exit $(circleci tests split --split-by=timings)

  setup_env_vars:
    docker:
      - image: cimg/node:18.20.0
    steps:
      - checkout
      - run:
          name: Configurar variables de entorno
          command: |
            echo 'export API_URL="https://echo-serv.tbxnet.com/v1/secret"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verificar variables de entorno
          command: |
            echo "API_URL: $API_URL"

workflows:
  version: 2

  # Workflow para ejecutar pruebas
  test_workflow:
    jobs:
      - setup
      - install_npm_force_resolution:
          requires:
            - setup
      - install_dependencies:
          requires:
            - install_npm_force_resolution
      - verify_dependencies:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - verify_dependencies

  # Workflow para configurar variables de entorno
  env_workflow:
    jobs:
      - setup
      - install_dependencies:
          requires:
            - setup
      - setup_env_vars:
          requires:
            - install_dependencies
